name: "Prompt Library CI pipeline"
on:
    push
jobs:
    prepare_docker_image:
        name: "Create CI Docker container"
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Prepare image
              run:  |
                docker build . -t "prompt-library"
                docker save -o ci-image.tar prompt-library
            - name: Store image
              uses: actions/upload-artifact@v4
              with:
                name: docker-ci-image 
                path: ci-image.tar
                retention-days: 1

    typecheck:
        name: "Typecheck"
        runs-on: ubuntu-22.04
        needs: prepare_docker_image
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: "Run CI container"
              uses: ./.github/actions/run-ci-container
            - name: Compile 
              run:  docker exec prompt-library bash -c "cd prompt-library && npm run typecheck"

    test:
        name: "Test"
        runs-on: ubuntu-22.04
        needs:  [typecheck, lint] 
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: "Run CI container"
              uses: ./.github/actions/run-ci-container
            - name: Test
              run:  docker exec prompt-library bash -c "cd prompt-library && npm run test"

    lint:
        name: "Lint"
        runs-on: ubuntu-22.04
        needs: prepare_docker_image
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: "Run CI container"
              uses: ./.github/actions/run-ci-container
            - name: Lint
              run:  docker exec prompt-library bash -c "cd prompt-library && npm run lint"

    teardown:
        name: "Teardown CI"
        runs-on: ubuntu-22.04
        if: always()
        needs: [typecheck, lint, test] 
        steps:
            - name: Remove CI image
              uses: geekyeggo/delete-artifact@v5
              with:
                name: docker-ci-image 
            
